# Generated by Django 5.0.6 on 2024-11-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('start_date_time', models.DateTimeField(auto_now_add=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('input', models.JSONField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lilota_store',
            },
        ),
    ]
